In [33]:
import numpy as np
import random


In [34]:
v=np.array([None]*20)

In [35]:

v

array([None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None], dtype=object)

In [36]:
type(v)

numpy.ndarray

In [37]:
z=np.zeros(10)

In [38]:
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [39]:
v[0]

In [40]:
v[1]

In [41]:
v[1]=42

In [42]:
v

array([None, 42, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None], dtype=object)

In [43]:
v[1:3]

array([42, None], dtype=object)

In [44]:
v

array([None, 42, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None], dtype=object)

In [45]:
a=np.array(range(15)).reshape(3,5)

In [46]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
a[0]

array([0, 1, 2, 3, 4])

In [48]:
a[1]

array([5, 6, 7, 8, 9])

In [49]:
a[1][4]

9

In [50]:
loc=(1,4)

In [51]:
a[loc]

9

In [52]:
a[1,4]

9

In [53]:
d=np.array(range(27)).reshape(3,9)

In [68]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [69]:
d[2][1]

19

In [56]:
def array(row,column):
    d=np.array([None]*(row*column)).reshape(row, column)
    return d

In [57]:
array(10,3)

array([[None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [126]:
x=array(10,10)

In [130]:
from PIL import Image

image = Image.open('fish.gif')
x[2][7]=image.show()

In [131]:
x

array([[None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None]], dtype=object)

In [108]:
z=(2,3,4)

In [109]:
y=(5,6,7)

In [110]:
z[0]

2

In [113]:
x[z[0],y[0]]

7

In [132]:
x=array(10,10)

In [133]:
x


array([[None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None],
       [None, None, None, None, None, None, None, None, None, None]], dtype=object)

In [134]:
x[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [135]:
x[10][11]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [138]:
x[9][1]=7

In [139]:
x[9][1]

7